name: torch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.7
  - ipython=9.5.0
  - ipykernel=6.30.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - numpy=2.3.3
  - pandas=2.3.3
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - matplotlib=3.10.7
  - contourpy=1.3.3
  - pillow=12.0.0
  - openpyxl=3.1.5
  - sympy=1.14.0
  - networkx=3.6.1
  - torch=2.9.1
  - torchvision=0.24.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - et_xmlfile=2.0.0
  - executing=2.2.1
  - exceptiongroup=1.3.0
  - filelock=3.20.0
  - fonttools=4.61.0
  - fsspec=2025.12.0
  - importlib-metadata=8.7.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - kiwisolver=1.4.9
  - matplotlib-inline=0.1.7
  - mpmath=1.3.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.5
  - setuptools=80.9.0
  - stack_data=0.6.3
  - threadpoolctl=3.6.0
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.13
  - zipp=3.23.0
  - ca-certificates=2025.10.5
  - bzip2=1.0.8
  - icu=75.1
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgfortran=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - llvm-openmp=21.1.3
  - ncurses=6.5
  - openssl=3.5.4
  - readline=8.2
  - tk=8.6.13
  - tornado=6.5.2
